version: "3.9"
services:
  mountebank:
    image: "bbyars/mountebank:2.8.1"
    ports:
      - "2525:2525"
      - "4545-4560:4545-4560"
    command:
      - "start"
    networks:
      - imposters

  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
      - "3000-4000:3000-4000"
      - "6990:6990"
    volumes:
      - "./config:/home/nonroot/.imposters"
      - "./log:/home/nonroot/outputs"
    networks:
      - imposters

networks:
  imposters: