global:
  correlationIdHeader: "X-Internal-Correlation-ID"

server:
  port: 3000
  readTimeoutSeconds: 15
  writeTimeoutSeconds: 15

logger:
  file: /home/nonroot/outputs/outputs.log
  level: debug

mountebank:
  host: localhost
  imposters:
    - name: list
      path: v1/planets
      port: 4545