[secrets]
enable = true

[secrets.db]
username = "user"
password = "pass"

[[secrets.apis]]
host = "external.api.io"
username = "ioUserName"
password = "ioPassword"

[[secrets.apis]]
host = "external.api.tls"
username = "tlsUserName"
password = "tlsPassword"