// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/planetwelcome.proto

package space

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string          `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Timestamp     string          `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *WelcomePayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetwelcome_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetwelcome_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_proto_planetwelcome_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *WelcomeMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WelcomeMessage) GetPayload() *WelcomePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WelcomePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalCode int32  `protobuf:"varint,1,opt,name=internal_code,json=internalCode,proto3" json:"internal_code,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WelcomePayload) Reset() {
	*x = WelcomePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetwelcome_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePayload) ProtoMessage() {}

func (x *WelcomePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetwelcome_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePayload.ProtoReflect.Descriptor instead.
func (*WelcomePayload) Descriptor() ([]byte, []int) {
	return file_proto_planetwelcome_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomePayload) GetInternalCode() int32 {
	if x != nil {
		return x.InternalCode
	}
	return 0
}

func (x *WelcomePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_planetwelcome_proto protoreflect.FileDescriptor

var file_proto_planetwelcome_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4f, 0x0a, 0x0e, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_planetwelcome_proto_rawDescOnce sync.Once
	file_proto_planetwelcome_proto_rawDescData = file_proto_planetwelcome_proto_rawDesc
)

func file_proto_planetwelcome_proto_rawDescGZIP() []byte {
	file_proto_planetwelcome_proto_rawDescOnce.Do(func() {
		file_proto_planetwelcome_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_planetwelcome_proto_rawDescData)
	})
	return file_proto_planetwelcome_proto_rawDescData
}

var file_proto_planetwelcome_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_planetwelcome_proto_goTypes = []interface{}{
	(*WelcomeMessage)(nil), // 0: space.WelcomeMessage
	(*WelcomePayload)(nil), // 1: space.WelcomePayload
}
var file_proto_planetwelcome_proto_depIdxs = []int32{
	1, // 0: space.WelcomeMessage.payload:type_name -> space.WelcomePayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_planetwelcome_proto_init() }
func file_proto_planetwelcome_proto_init() {
	if File_proto_planetwelcome_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_planetwelcome_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetwelcome_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_planetwelcome_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_planetwelcome_proto_goTypes,
		DependencyIndexes: file_proto_planetwelcome_proto_depIdxs,
		MessageInfos:      file_proto_planetwelcome_proto_msgTypes,
	}.Build()
	File_proto_planetwelcome_proto = out.File
	file_proto_planetwelcome_proto_rawDesc = nil
	file_proto_planetwelcome_proto_goTypes = nil
	file_proto_planetwelcome_proto_depIdxs = nil
}
