// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/planetdetails.proto

package space

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanetDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type             string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EquatorialRadius *EquatorialRadius `protobuf:"bytes,4,opt,name=equatorial_radius,json=equatorialRadius,proto3" json:"equatorial_radius,omitempty"`
	Mass             *Mass             `protobuf:"bytes,5,opt,name=mass,proto3" json:"mass,omitempty"`
	Volume           *Volume           `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Density          *Density          `protobuf:"bytes,7,opt,name=density,proto3" json:"density,omitempty"`
	Satellites       []string          `protobuf:"bytes,8,rep,name=satellites,proto3" json:"satellites,omitempty"`
}

func (x *PlanetDetails) Reset() {
	*x = PlanetDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetdetails_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanetDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetDetails) ProtoMessage() {}

func (x *PlanetDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetdetails_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetDetails.ProtoReflect.Descriptor instead.
func (*PlanetDetails) Descriptor() ([]byte, []int) {
	return file_proto_planetdetails_proto_rawDescGZIP(), []int{0}
}

func (x *PlanetDetails) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlanetDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanetDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanetDetails) GetEquatorialRadius() *EquatorialRadius {
	if x != nil {
		return x.EquatorialRadius
	}
	return nil
}

func (x *PlanetDetails) GetMass() *Mass {
	if x != nil {
		return x.Mass
	}
	return nil
}

func (x *PlanetDetails) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *PlanetDetails) GetDensity() *Density {
	if x != nil {
		return x.Density
	}
	return nil
}

func (x *PlanetDetails) GetSatellites() []string {
	if x != nil {
		return x.Satellites
	}
	return nil
}

type EquatorialRadius struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MetricUnit string `protobuf:"bytes,2,opt,name=metric_unit,json=metricUnit,proto3" json:"metric_unit,omitempty"`
}

func (x *EquatorialRadius) Reset() {
	*x = EquatorialRadius{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetdetails_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquatorialRadius) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquatorialRadius) ProtoMessage() {}

func (x *EquatorialRadius) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetdetails_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquatorialRadius.ProtoReflect.Descriptor instead.
func (*EquatorialRadius) Descriptor() ([]byte, []int) {
	return file_proto_planetdetails_proto_rawDescGZIP(), []int{1}
}

func (x *EquatorialRadius) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EquatorialRadius) GetMetricUnit() string {
	if x != nil {
		return x.MetricUnit
	}
	return ""
}

type Mass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MetricUnit string `protobuf:"bytes,2,opt,name=metric_unit,json=metricUnit,proto3" json:"metric_unit,omitempty"`
}

func (x *Mass) Reset() {
	*x = Mass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetdetails_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mass) ProtoMessage() {}

func (x *Mass) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetdetails_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mass.ProtoReflect.Descriptor instead.
func (*Mass) Descriptor() ([]byte, []int) {
	return file_proto_planetdetails_proto_rawDescGZIP(), []int{2}
}

func (x *Mass) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Mass) GetMetricUnit() string {
	if x != nil {
		return x.MetricUnit
	}
	return ""
}

type Volume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MetricUnit string `protobuf:"bytes,2,opt,name=metric_unit,json=metricUnit,proto3" json:"metric_unit,omitempty"`
}

func (x *Volume) Reset() {
	*x = Volume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetdetails_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetdetails_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_proto_planetdetails_proto_rawDescGZIP(), []int{3}
}

func (x *Volume) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Volume) GetMetricUnit() string {
	if x != nil {
		return x.MetricUnit
	}
	return ""
}

type Density struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MetricUnit string `protobuf:"bytes,2,opt,name=metric_unit,json=metricUnit,proto3" json:"metric_unit,omitempty"`
}

func (x *Density) Reset() {
	*x = Density{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetdetails_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Density) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Density) ProtoMessage() {}

func (x *Density) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetdetails_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Density.ProtoReflect.Descriptor instead.
func (*Density) Descriptor() ([]byte, []int) {
	return file_proto_planetdetails_proto_rawDescGZIP(), []int{4}
}

func (x *Density) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Density) GetMetricUnit() string {
	if x != nil {
		return x.MetricUnit
	}
	return ""
}

var File_proto_planetdetails_proto protoreflect.FileDescriptor

var file_proto_planetdetails_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0x9f, 0x02, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x11,
	0x65, 0x71, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x45, 0x71, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x52, 0x10, 0x65, 0x71, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x4d, 0x61, 0x73, 0x73, 0x52, 0x04, 0x6d,
	0x61, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65,
	0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x52, 0x07, 0x64, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x74, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x10, 0x45, 0x71, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x22,
	0x3d, 0x0a, 0x04, 0x4d, 0x61, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x3f,
	0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x22,
	0x40, 0x0a, 0x07, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x55, 0x6e, 0x69,
	0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_planetdetails_proto_rawDescOnce sync.Once
	file_proto_planetdetails_proto_rawDescData = file_proto_planetdetails_proto_rawDesc
)

func file_proto_planetdetails_proto_rawDescGZIP() []byte {
	file_proto_planetdetails_proto_rawDescOnce.Do(func() {
		file_proto_planetdetails_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_planetdetails_proto_rawDescData)
	})
	return file_proto_planetdetails_proto_rawDescData
}

var file_proto_planetdetails_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_planetdetails_proto_goTypes = []interface{}{
	(*PlanetDetails)(nil),    // 0: space.PlanetDetails
	(*EquatorialRadius)(nil), // 1: space.EquatorialRadius
	(*Mass)(nil),             // 2: space.Mass
	(*Volume)(nil),           // 3: space.Volume
	(*Density)(nil),          // 4: space.Density
}
var file_proto_planetdetails_proto_depIdxs = []int32{
	1, // 0: space.PlanetDetails.equatorial_radius:type_name -> space.EquatorialRadius
	2, // 1: space.PlanetDetails.mass:type_name -> space.Mass
	3, // 2: space.PlanetDetails.volume:type_name -> space.Volume
	4, // 3: space.PlanetDetails.density:type_name -> space.Density
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_planetdetails_proto_init() }
func file_proto_planetdetails_proto_init() {
	if File_proto_planetdetails_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_planetdetails_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanetDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetdetails_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquatorialRadius); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetdetails_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetdetails_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Volume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetdetails_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Density); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_planetdetails_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_planetdetails_proto_goTypes,
		DependencyIndexes: file_proto_planetdetails_proto_depIdxs,
		MessageInfos:      file_proto_planetdetails_proto_msgTypes,
	}.Build()
	File_proto_planetdetails_proto = out.File
	file_proto_planetdetails_proto_rawDesc = nil
	file_proto_planetdetails_proto_goTypes = nil
	file_proto_planetdetails_proto_depIdxs = nil
}
