// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/planetlist.proto

package space

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanetListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PlanetListItem) Reset() {
	*x = PlanetListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanetListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetListItem) ProtoMessage() {}

func (x *PlanetListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetListItem.ProtoReflect.Descriptor instead.
func (*PlanetListItem) Descriptor() ([]byte, []int) {
	return file_proto_planetlist_proto_rawDescGZIP(), []int{0}
}

func (x *PlanetListItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlanetListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlanetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanetList []*PlanetListItem `protobuf:"bytes,1,rep,name=planetList,proto3" json:"planetList,omitempty"`
}

func (x *PlanetList) Reset() {
	*x = PlanetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_planetlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetList) ProtoMessage() {}

func (x *PlanetList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_planetlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetList.ProtoReflect.Descriptor instead.
func (*PlanetList) Descriptor() ([]byte, []int) {
	return file_proto_planetlist_proto_rawDescGZIP(), []int{1}
}

func (x *PlanetList) GetPlanetList() []*PlanetListItem {
	if x != nil {
		return x.PlanetList
	}
	return nil
}

var File_proto_planetlist_proto protoreflect.FileDescriptor

var file_proto_planetlist_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22,
	0x34, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_planetlist_proto_rawDescOnce sync.Once
	file_proto_planetlist_proto_rawDescData = file_proto_planetlist_proto_rawDesc
)

func file_proto_planetlist_proto_rawDescGZIP() []byte {
	file_proto_planetlist_proto_rawDescOnce.Do(func() {
		file_proto_planetlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_planetlist_proto_rawDescData)
	})
	return file_proto_planetlist_proto_rawDescData
}

var file_proto_planetlist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_planetlist_proto_goTypes = []interface{}{
	(*PlanetListItem)(nil), // 0: space.PlanetListItem
	(*PlanetList)(nil),     // 1: space.PlanetList
}
var file_proto_planetlist_proto_depIdxs = []int32{
	0, // 0: space.PlanetList.planetList:type_name -> space.PlanetListItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_planetlist_proto_init() }
func file_proto_planetlist_proto_init() {
	if File_proto_planetlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_planetlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanetListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_planetlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_planetlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_planetlist_proto_goTypes,
		DependencyIndexes: file_proto_planetlist_proto_depIdxs,
		MessageInfos:      file_proto_planetlist_proto_msgTypes,
	}.Build()
	File_proto_planetlist_proto = out.File
	file_proto_planetlist_proto_rawDesc = nil
	file_proto_planetlist_proto_goTypes = nil
	file_proto_planetlist_proto_depIdxs = nil
}
